package com.example.dao.brand;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;




// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {


    private final DaoConfig brandDaoConfig;

    private final BrandDao brandDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>daoConfigMap){
        super(db);

      
        brandDaoConfig = daoConfigMap.get(BrandDao.class).clone();
        brandDaoConfig.initIdentityScope(type);

       brandDao = new BrandDao(brandDaoConfig, this);

         registerDao(Brand.class, brandDao);
    }   
    
    public void clear() {
       
        brandDaoConfig.getIdentityScope().clear();
    }

    
    public BrandDao getBrandDao() {
        return brandDao;
    }

}
